### ISSUE TITLE
Simplify invocation of docbot action

### ISSUE THREAD

**Issue by maxsxu** [apache/pulsar-test-infra#67]
### Motivation
The [Current invocation of docbot](https://github.com/apache/pulsar/blob/46b1239a23fd2a250b009df1e9b4a65341d299a7/.github/workflows/ci-documentbot.yml):

```
jobs:
  label:
    steps:
      - name: Checkout action
        uses: actions/checkout@v3
        with:
          repository: apache/pulsar-test-infra
          ref: master

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Labeling
        uses: ./docbot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LABEL_WATCH_LIST: 'doc,doc-required,doc-not-needed,doc-complete'
          LABEL_MISSING: 'doc-label-missing'
```

These steps before Labeling should be organized into the action itself, the desired invocation should be illustrated below:

```
jobs:
  label:
    steps:
      - name: Labeling
        uses: pulsar/pulsar-test-infra/docbot@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LABEL_WATCH_LIST: 'doc,doc-required,doc-not-needed,doc-complete'
          LABEL_MISSING: 'doc-label-missing'
```

inspired from https://github.com/apache/pulsar-test-infra/issues/58#issuecomment-1225889058
